In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./data/sample_survey_results_public.csv")
df_schema = pd.read_csv("./data/survey_results_schema.csv")

In [4]:
df.shape

(16115, 61)

In [3]:
df.head()

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
0,63311,I am a developer by profession,Yes,27.0,16,Monthly,40000.0,109956.0,Brazil,Brazilian real,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;ASP.NET Core;Vue.js,Angular;ASP.NET Core,Just as welcome now as I felt last year,80.0,8,7
1,65180,I am a developer by profession,Yes,NaN,16,NaN,NaN,NaN,Dominican Republic,Dominican peso,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,NaN,6,3
2,42378,"I am not primarily a developer, but I write co...",No,NaN,12,NaN,NaN,NaN,United States,NaN,...,NaN,NaN,NaN,"Another engineering discipline (such as civil,...",NaN,NaN,NaN,NaN,35,25
3,42192,I am a developer by profession,Yes,NaN,15,NaN,NaN,NaN,Brazil,NaN,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,NaN,5,Less than 1 year
4,21072,I am a developer by profession,Yes,24.0,20,Monthly,16211.0,2712.0,India,Indian rupee,...,Neither easy nor difficult,Too long,No,"Computer science, computer engineering, or sof...",Angular;Spring,Angular;Spring,A lot more welcome now than last year,45.0,4,Less than 1 year

In [5]:
pd.set_option("display.max_columns", 60)

In [6]:
df.head()

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,...,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
0,63311,I am a developer by profession,Yes,27.0,16,Monthly,40000.0,109956.0,Brazil,Brazilian real,BRL,DynamoDB;Microsoft SQL Server;MongoDB;Redis,Microsoft SQL Server,"Developer, full-stack;DevOps specialist","Associate degree (A.A., A.S., etc.)","Independent contractor, freelancer, or self-em...",White or of European descent,Man,"Flex time or a flexible schedule;Languages, fr...",Slightly satisfied,"Iâ€™m not actively looking, but I am open to new...",C#;JavaScript;SQL,C#;HTML/CSS;JavaScript;SQL;TypeScript,.NET Core;Node.js;Unity 3D,.NET;.NET Core;Node.js;Unity 3D,Gitlab;Slack,Confluence;Jira;Github;Gitlab;Facebook Workpla...,No,Extremely important,Not at all important/not necessary,...,Company reviews from third party sites (e.g. G...,Every few months,Not sure,No,Yes,Sometimes: 1-2 days per month but less than we...,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,Windows,20 to 99 employees,AWS;Microsoft Azure;Slack Apps and Integrations,AWS;Docker;Microsoft Azure;Slack Apps and Inte...,NaN,Straight / Heterosexual,Yes,"Yes, somewhat",A few times per month or weekly,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;ASP.NET Core;Vue.js,Angular;ASP.NET Core,Just as welcome now as I felt last year,80.0,8,7
1,65180,I am a developer by profession,Yes,NaN,16,NaN,NaN,NaN,Dominican Republic,Dominican peso,DOP,NaN,NaN,"Developer, back-end",Some college/university study without earning ...,"Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,Very dissatisfied,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very important,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,NaN,6,3
2,42378,"I am not primarily a developer, but I write co...",No,NaN,12,NaN,NaN,NaN,United States,NaN,NaN,NaN,NaN,"Database administrator;Designer;Engineer, data",Some college/university study without earning ...,"Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not at all important/not necessary,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Another engineering discipline (such as civil,...",NaN,NaN,NaN,NaN,35,25
3,42192,I am a developer by profession,Yes,NaN,15,NaN,NaN,NaN,Brazil,NaN,NaN,NaN,NaN,"Academic researcher;Developer, full-stack;Deve...","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed part-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very important,...,NaN,NaN,Not sure,NaN,No,NaN,NaN,NaN,Stack Overflow (public Q&A for anyone who code...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not sure/can't remember,Neutral,NaN,Multiple times per day,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,NaN,5,Less than 1 year
4,21072,I am a developer by profession,Yes,24.0,20,Monthly,16211.0,2712.0,India,Indian rupee,INR,MySQL;Oracle,MySQL;Oracle,"Developer, full-stack","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,Man,"Industry that Iâ€™d be working in;Languages, fra...",Very dissatisfied,I am actively looking for a job,Java;TypeScript,Java;SQL,Hadoop;Node.js;Xamarin,NaN,Jira;Github;Gitlab;Microsoft Teams;Microsoft A...,NaN,No,Extremely important,Not at all important/not necessary,...,"Read company media, such as employee blogs or ...",Every few months,Not sure,Onboarding? What onboarding?,No,Often: 1-2 days per week or more,Visit developer communities like Stack Overflow,Annoyed,Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow,Linux-based,10 to 19 employees,MacOS;Windows,Linux,I have some influence,NaN,Not sure/can't remember,Neutral,NaN,Multiple times per day,Neither easy nor difficult,Too long,No,"Computer science, computer engineering, or sof...",Angular;Spring,Angular;Spring,A lot more welcome now than last year,45.0,4,Less than 1 year

In [8]:
df_schema

                Column                                       QuestionText
0           Respondent  Randomized respondent ID number (not in order ...
1           MainBranch  Which of the following options best describes ...
2             Hobbyist                            Do you code as a hobby?
3                  Age  What is your age (in years)? If you prefer not...
4           Age1stCode  At what age did you write your first line of c...
..                 ...                                                ...
56  WebframeWorkedWith  Which web frameworks have you done extensive d...
57       WelcomeChange  Compared to last year, how welcome do you feel...
58         WorkWeekHrs  On average, how many hours per week do you wor...
59           YearsCode  Including any education, how many years have y...
60        YearsCodePro  NOT including education, how many years have y...

[61 rows x 2 columns]

In [10]:
df_schema[df_schema["Column"] == "ConvertedComp"]["QuestionText"].values

array(['Salary converted to annual USD salaries using the exchange rate on 2020-02-19, assuming 12 working months and 50 working weeks.'],
      dtype=object)

In [27]:
df["ConvertedComp"]

0        109956.0
1             NaN
2             NaN
3             NaN
4          2712.0
           ...
16110         NaN
16111         NaN
16112         NaN
16113         NaN
16114         NaN
Name: ConvertedComp, Length: 16115, dtype: float64

In [11]:
df_schema.set_index("Column", inplace=True)

In [12]:
df_schema

                                                         QuestionText
Column
Respondent          Randomized respondent ID number (not in order ...
MainBranch          Which of the following options best describes ...
Hobbyist                                      Do you code as a hobby?
Age                 What is your age (in years)? If you prefer not...
Age1stCode          At what age did you write your first line of c...
...                                                               ...
WebframeWorkedWith  Which web frameworks have you done extensive d...
WelcomeChange       Compared to last year, how welcome do you feel...
WorkWeekHrs         On average, how many hours per week do you wor...
YearsCode           Including any education, how many years have y...
YearsCodePro        NOT including education, how many years have y...

[61 rows x 1 columns]

In [39]:
df_schema.loc["Hobbyist"].values

array(['Do you code as a hobby?'], dtype=object)

In [13]:
df['Hobbyist'].count()

16107

In [43]:
df["Hobbyist"].value_counts()

Yes    12641
No      3466
Name: Hobbyist, dtype: int64

### Grouping

In [44]:
country_grp = df.groupby(["Country"])

In [45]:
df["Country"].value_counts()

United States     3120
India             2112
Germany            977
United Kingdom     971
Canada             562
                  ...
Burkina Faso         1
Swaziland            1
San Marino           1
Haiti                1
Belize               1
Name: Country, Length: 165, dtype: int64

In [46]:
country_grp.get_group("United States")

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,...,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
2,42378,"I am not primarily a developer, but I write co...",No,NaN,12,NaN,NaN,NaN,United States,NaN,NaN,NaN,NaN,"Database administrator;Designer;Engineer, data",Some college/university study without earning ...,"Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not at all important/not necessary,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Another engineering discipline (such as civil,...",NaN,NaN,NaN,NaN,35,25
10,54515,I code primarily as a hobby,Yes,22.0,15,NaN,NaN,NaN,United States,NaN,NaN,Cassandra;Microsoft SQL Server;Oracle,Elasticsearch;Firebase;MySQL,NaN,"Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Student,Hispanic or Latino/a/x,Man,NaN,NaN,NaN,Go;Kotlin;Perl;PHP;Scala,C;C#;C++;HTML/CSS;Java;JavaScript;Objective-C;...,.NET;.NET Core;Flutter;Node.js;React Native,Xamarin,Facebook Workplace;Microsoft Teams;Microsoft A...,Github,NaN,NaN,NaN,...,NaN,Every few months,No,NaN,No,NaN,Visit developer communities like Stack Overflow,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow,MacOS,NaN,Android;Google Cloud Platform;Heroku;IBM Cloud...,Arduino;AWS;iOS;Linux;MacOS;Windows,NaN,Straight / Heterosexual,Yes,"Yes, somewhat",I have never participated in Q&A on Stack Over...,Daily or almost daily,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;Angular.js;ASP.NET;ASP.NET Core;React.js,jQuery;Ruby on Rails,Just as welcome now as I felt last year,NaN,3,NaN
12,3091,I am a developer by profession,Yes,NaN,20,Yearly,500000.0,500000.0,United States,United States dollar,USD,MongoDB,MongoDB,"Database administrator;Designer;Developer, bac...","Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",White or of European descent,Man,"Languages, frameworks, and other technologies ...",Very satisfied,I am not interested in new job opportunities,Python,C#;Python,NaN,.NET Core;Xamarin,Github;Trello,Github;Trello,No,Neutral,Fairly important,...,"Read company media, such as employee blogs or ...",Once every few years,Yes,Yes,Yes,Occasionally: 1-2 days per quarter but less th...,Start a free trial;Ask developers I know/work ...,Amused,Stack Overflow (public Q&A for anyone who codes),Play games;Go for a walk or other physical act...,MacOS,2 to 9 employees,AWS;MacOS,AWS;MacOS,NaN,Straight / Heterosexual,Yes,"Yes, somewhat",A few times per week,A few times per week,Neither easy nor difficult,Appropriate in length,No,Mathematics or statistics,NaN,ASP.NET Core;Vue.js,Just as welcome now as I felt last year,40.0,25,22
14,49530,I am a developer by profession,Yes,46.0,12,Yearly,130000.0,130000.0,United States,United States dollar,USD,Microsoft SQL Server;MongoDB;MySQL;PostgreSQL;...,Microsoft SQL Server,"Database administrator;Developer, back-end;Dev...","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,Flex time or a flexible schedule;Remote work o...,Slightly satisfied,"Iâ€™m not actively looking, but I am open to new...",C#;Go;JavaScript;Python;Ruby;TypeScript,C#;HTML/CSS;JavaScript;SQL;TypeScript,.NET;.NET Core;Node.js,.NET;.NET Core;Node.js,Microsoft Azure,"Github;Google Suite (Docs, Meet, etc)",No,Neutral,Fairly important,...,Company reviews from third party sites (e.g. G...,Once a year,Not sure,Onboarding? What onboarding?,No,Often: 1-2 days per week or more,Start a free trial;Ask developers I know/work ...,Indifferent,Stack Overflow (public Q&A for anyone who codes),Call a coworker or friend;Visit Stack Overflow...,Windows,2 to 9 employees,Android;Arduino;Linux;Microsoft Azure,NaN,I have a great deal of influence,Straight / Heterosexual,No,"No, not at all",NaN,Multiple times per day,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;ASP.NET Core,Angular;Angular.js;ASP.NET;ASP.NET Core;jQuery,Just as welcome now as I felt last year,45.0,34,24
17,50272,I am a developer by profession,No,62.0,12,Yearly,140000.0,140000.0,United States,United States dollar,USD,MySQL;Oracle,MySQL;Oracle,"Developer, back-end;Developer, desktop or ente...","Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed full-time,White or of European descent,Man,Flex time or a flexible schedule;Office enviro...,Slightly satisfied,I am not interested in new job opportunities,Bash/Shell/PowerShell;Java;Perl;SQL,Bash/Shell/PowerShell;HTML/CSS;Java;Perl;SQL,NaN,NaN,Confluence;Jira;Slack,Confluence;Jira;Github;Slack,Not sure,Neutral,Fairly important,...,Company reviews from third party sites (e.g. G...,NaN,Not sure,No,No,Often: 1-2 days per week or more,NaN,Annoyed,Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Go for a walk or oth...,Linux-based,100 to 499 employees,Linux,Linux;MacOS,I have little or no influence,Gay or Lesbian,No,"No, not really",NaN,A few times per week,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,45.0,More than 50 years,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16089,20372,I am a developer by profession,No,26.0,18,Yearly,70000.0,70000.0,United States,United States dollar,USD,Couchbase;PostgreSQL;Redis;SQLite,DynamoDB;Elasticsearch;Firebase;MySQL;PostgreS...,"Developer, full-stack","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,Biracial,Man,"Languages, frameworks, and other technologies ...",Slightly satisfied,"Iâ€™m not actively looking, but I am open to new...",Bash/Shell/PowerShell;C#;C++;Go;HTML/CSS;Pytho...,Bash/Shell/PowerShell;C#;C++;HTML/CSS;JavaScri...,Node.js;React Native;Unity 3D,Node.js;React Native,"Github;Gitlab;Google Suite (Docs, Meet, etc)","Github;Gitlab;Slack;Google Suite (Docs, Meet, ...",No,Somewhat important,Fairly important,...,Personal network - friends or family,Once a year,Not sure,Onboarding? What onboarding?,No,Sometimes: 1-2 days per month but less than we...,Start a free trial;Visit developer communities...,"Hello, old friend",Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow;Go for a walk or other ph...,MacOS,20 to 99 employees,Docker;iOS;Kubernetes;Linux;MacOS;Windows,AWS;iOS;MacOS;Windows,I have some influence,Straight / Heterosexual,Not sure/can't remember,"No, not at all",NaN,A few times per month or weekly,Neither easy nor difficult,Too long,No,"Computer science, computer engineering, or sof...",Express;Gatsby;React.js;Ruby on Rails,Express;Gatsby;React.js;Ruby on Rails,Somewhat more welcome now than last year,45.0,9,5
16097,26042,I am a developer by profession,Yes,49.0,12,Yearly,220000.0,220000.0,United States,United States dollar,USD,MariaDB;PostgreSQL;Redis;SQLite,MariaDB;PostgreSQL;Redis;SQLite,Data scientist or machine learning specialist;...,"Other doctoral degree (Ph.D., Ed.D., etc.)",Employed full-time,White or of European descent,Man,"Languages, frameworks, and other technologies ...",Very satisfied,I am not interested in new job opportunities,Bash/Shell/PowerShell;C++;HTML/CSS;Python;SQL,Bash/Shell/PowerShell;C++;HTML/CSS;Python;SQL,Node.js;Pandas;Torch/PyTorch,.NET;Node.js;Torch/PyTorch,Github;Microsoft Teams;Microsoft Azure,Github;Microsoft Teams;Microsoft Azure,Yes,Extremely important,Very important,...,NaN,Every few months,Yes,Yes,No,Often: 1-2 days per week or more,Start a free trial;Visit developer communities...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Meditate;Visit Stack Overflow;Go for a walk or...,Linux-based,"10,000 or more employees",Docker;Kubernetes;Linux;Microsoft Azure,Docker;Kubernetes;Linux;Microsoft Azure;Windows,I have some influence,Straight / Heterosexual,Yes,"Yes, definitely",Less than once per month or monthly,Multiple times per day,Easy,Too short,No,"A natural science (such as biology, chemistry,...",Express;jQuery;Vue.js,Express;jQuery;Vue.js,Somewhat more welcome now than last year,55.0,35,12
16100,25290,I am a developer by profession,Yes,29.0,10,Yearly,74000.0,74000.0,United States,United States dollar,USD,MongoDB;Oracle,Oracle,"Developer, back-end;Developer, front-end;Devel...","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Woman,Diversity of the company or organization;Flex ...,Slightly satisfied,"Iâ€™m not actively looking, but I am open to new...",C#;HTML/CSS;JavaScript;SQL;Swift;TypeScript,C#;HTML/CSS;JavaScript;TypeScript,.NET Core;Ansible;React Native,.NET;.NET Core;Node.js,Jira;Microsoft Teams;Stack Overflow for Teams,Jira;Slack;Microsoft Teams,Yes,Extremely important,Somewhat important,...,"Read company media, such as employee blogs or ...",Once a year,No,Yes,No,Rarely: 1-2 days per year or less,NaN,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Meditate;Play games;Call a coworker or friend;...,Windows,"10,000 or more employees",NaN,NaN,I have little or no influence,NaN,Yes,"Yes, somewhat",Less than once per month or monthly,A few times per month or weekly,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;ASP.NET Core,Angular;Angular.js;ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,40.0,12,7
16101,84,I am a developer by profession,Yes,25.0,12,Monthly,NaN,NaN,United States,United States dollar,USD,NaN,Oracle;PostgreSQL,"Developer, back-end;Developer, front-end;Devel...","Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,Flex time or a flexible schedule;Specific depa...,Slightly satisfied,"Iâ€™m not actively looking, but I am open to new...",NaN,Bash/Shell/PowerShell;C;C#;C++;HTML/CSS;Java;P...,NaN,.NET;.NET Core,NaN,Github;Slack;Microsoft Teams;Google Suite (Doc...,No,Neutral,Somewhat important,...,Directly asking current or past employees at t...,Once a year,Not sure,No,No,Often: 1-2 days per week or more,Start a free trial,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Do other work and come back later,Windows,2 to 9 employees,NaN,Android;Arduino;Linux;Raspberry Pi;Windows,I have some influence,Straight / Heterosexual,Yes,"No, not really",Less than once per month or monthly,Daily or almost daily,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,jQuery,Just as welcome now as I felt last year,60.0,13,2
16114,53862,I code primarily as a hobby,Yes,NaN,11,NaN,NaN,NaN,United States,NaN,NaN,PostgreSQL;SQLite,MariaDB;MySQL;PostgreSQL;SQLite,NaN,"Secondary school (e.g. American high school, G...",Student,Middle Eastern;White or of European descent;Bi...,Man,NaN,NaN,NaN,C#;C++;HTML/CSS;Java;JavaScript;Python;Ruby;SQL,C#;C++;HTML/CSS;Java;JavaScript;TypeScript,Node.js;React Native;TensorFlow;Unity 3D,Node.js,Gitlab;Trello,Github;Gitlab;Trello,NaN,NaN,NaN,...,NaN,Every few months,No,NaN,No,NaN,Ask developers I know/work with;Visit develope...,Annoyed,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Do other work and come ba...,Linux-based,NaN,Docker;Linux;Raspberry Pi,Linux;Raspberry Pi,NaN,Gay or Lesbian,Yes,Not sure,I have never participated in Q&A on Stack Over...,Daily or almost daily,Easy,Appropriate in length,No,NaN,Angular;Angular.js;Express;React.js;Vue.js,Express,Just as welcome now as I felt last year,NaN,5,NaN

In [50]:
df_schema.loc["NEWCollabToolsDesireNextYear"].values

array(['Which collaboration tools have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you worked with the tool and want to continue to do so, please check both boxes in that row.)'],
      dtype=object)

In [47]:
# grouping by filter
filt = df['Country']=='Bangladesh'
df.loc[filt]['NEWCollabToolsDesireNextYear'].value_counts()

Github                                                                                   12
Github;Stack Overflow for Teams                                                           3
Github;Trello                                                                             3
Gitlab                                                                                    3
Jira;Github;Gitlab;Google Suite (Docs, Meet, etc)                                         2
                                                                                         ..
Github;Gitlab;Facebook Workplace;Trello;Google Suite (Docs, Meet, etc)                    1
Github;Microsoft Teams;Trello;Google Suite (Docs, Meet, etc);Stack Overflow for Teams     1
Jira;Github;Slack;Google Suite (Docs, Meet, etc);Stack Overflow for Teams                 1
Jira;Github;Slack                                                                         1
Github;Gitlab;Slack                                                                       1
Name: NEWCollabToolsDesireNextYear, Length: 61, dtype: int64

In [48]:
country_grp['Employment'].value_counts().head(50)

Country      Employment
Afghanistan  Employed full-time                                        9
             Employed part-time                                        3
             Independent contractor, freelancer, or self-employed      3
             Student                                                   2
             Not employed, but looking for work                        1
Albania      Employed full-time                                        6
             Not employed, but looking for work                        1
Algeria      Employed full-time                                        8
             Student                                                   6
             Employed part-time                                        4
             Independent contractor, freelancer, or self-employed      3
             Not employed, but looking for work                        2
Andorra      Independent contractor, freelancer, or self-employed      1
Angola       Employed full-time                                        1
             Not employed, but looking for work                        1
             Student                                                   1
Argentina    Employed full-time                                       51
             Independent contractor, freelancer, or self-employed     14
             Student                                                   6
             Employed part-time                                        4
             Not employed, but looking for work                        4
Armenia      Employed full-time                                        8
             Independent contractor, freelancer, or self-employed      2
             Employed part-time                                        1
Australia    Employed full-time                                      236
             Student                                                  30
             Independent contractor, freelancer, or self-employed     25
             Not employed, but looking for work                       13
             Employed part-time                                       12
             Retired                                                   2
             Not employed, and not looking for work                    1
Austria      Employed full-time                                       68
             Student                                                  23
             Employed part-time                                       19
             Independent contractor, freelancer, or self-employed     14
             Not employed, but looking for work                        2
Azerbaijan   Employed full-time                                        8
             Student                                                   4
             Employed part-time                                        1
             Not employed, but looking for work                        1
Bahamas      Independent contractor, freelancer, or self-employed      1
Bahrain      Employed full-time                                        4
Bangladesh   Employed full-time                                       68
             Student                                                  24
             Not employed, but looking for work                       17
             Independent contractor, freelancer, or self-employed     12
             Employed part-time                                        5
Barbados     Employed full-time                                        1
Belarus      Employed full-time                                       22
             Independent contractor, freelancer, or self-employed      8
Name: Employment, dtype: int64

In [51]:
country_grp['ConvertedComp'].median().loc['Germany']

64859.0

### aggrigation

In [52]:
country_grp['ConvertedComp'].agg(['median', 'mean'])

                                       median          mean
Country
Afghanistan                           13199.0  52174.500000
Albania                               10704.0  13296.000000
Algeria                               14400.0  14400.000000
Andorra                                   NaN           NaN
Angola                                 5736.0   5736.000000
...                                       ...           ...
Venezuela, Bolivarian Republic of...   4800.0   7482.785714
Viet Nam                              10086.0  22873.600000
Yemen                                 36000.0  36000.000000
Zambia                                 1632.0   1632.000000
Zimbabwe                              90600.0  90600.000000

[165 rows x 2 columns]

In [53]:
country_grp['ConvertedComp'].agg(['median', 'mean']).loc['Canada']

median     65799.000000
mean      102923.195195
Name: Canada, dtype: float64

In [54]:
filt = df['Country']=='Bangladesh'
df.loc[filt]['LanguageWorkedWith'].str.contains('Python').sum()

41

In [55]:
df.loc[filt]['Employment'].str.contains('Student').value_counts()

False    102
True      24
Name: Employment, dtype: int64

In [57]:
country_usg_python = country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

In [58]:
country_usg_python

Country
Afghanistan                              5
Albania                                  1
Algeria                                 13
Andorra                                  0
Angola                                   0
                                        ..
Venezuela, Bolivarian Republic of...     9
Viet Nam                                19
Yemen                                    0
Zambia                                   1
Zimbabwe                                 2
Name: LanguageWorkedWith, Length: 165, dtype: int64

#### Quetion: Find the repondent country Name??

In [ ]:
# country_respondent = df['Country'].value_counts()

In [60]:
python_df = pd.concat([country_respondent, country_usg_python], axis='columns', sort=False)

In [61]:
python_df

                Country  LanguageWorkedWith
United States      3120                1505
India              2112                 680
Germany             977                 417
United Kingdom      971                 394
Canada              562                 267
...                 ...                 ...
Burkina Faso          1                   1
Swaziland             1                   1
San Marino            1                   0
Haiti                 1                   0
Belize                1                   1

[165 rows x 2 columns]

In [62]:
python_df.rename(columns={'Country':'NumRespondent', 'LanguageWorkedWith':'KnowsPython'}, inplace=True)

In [63]:
python_df

                NumRespondent  KnowsPython
United States            3120         1505
India                    2112          680
Germany                   977          417
United Kingdom            971          394
Canada                    562          267
...                       ...          ...
Burkina Faso                1            1
Swaziland                   1            1
San Marino                  1            0
Haiti                       1            0
Belize                      1            1

[165 rows x 2 columns]

In [64]:
# percentage knows python = part/whole*100
python_df['PctKnowsPython']=python_df['KnowsPython']/python_df['NumRespondent'] * 100

In [65]:
python_df.head()

                NumRespondent  KnowsPython  PctKnowsPython
United States            3120         1505       48.237179
India                    2112          680       32.196970
Germany                   977          417       42.681679
United Kingdom            971          394       40.576725
Canada                    562          267       47.508897

In [66]:
# sorting_new_df
python_df.sort_values(by='PctKnowsPython', ascending=False,inplace=True)

In [67]:
python_df

                           NumRespondent  KnowsPython  PctKnowsPython
Belize                                 1            1           100.0
Syrian Arab Republic                   2            2           100.0
Swaziland                              1            1           100.0
Burkina Faso                           1            1           100.0
Namibia                                1            1           100.0
...                                  ...          ...             ...
Qatar                                  4            0             0.0
Congo, Republic of the...              2            0             0.0
Sierra Leone                           2            0             0.0
Madagascar                             3            0             0.0
Isle of Man                            1            0             0.0

[165 rows x 3 columns]