In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./data/sample_survey_results_public.csv")
df_schema = pd.read_csv("./data/survey_results_schema.csv")

In [33]:
df.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'Age', 'Age1stCode', 'CompFreq',
       'CompTotal', 'ConvertedComp', 'Country', 'CurrencyDesc',
       'CurrencySymbol', 'DatabaseDesireNextYear', 'DatabaseWorkedWith',
       'DevType', 'EdLevel', 'Employment', 'Ethnicity', 'Gender', 'JobFactors',
       'JobSat', 'JobSeek', 'LanguageDesireNextYear', 'LanguageWorkedWith',
       'MiscTechDesireNextYear', 'MiscTechWorkedWith',
       'NEWCollabToolsDesireNextYear', 'NEWCollabToolsWorkedWith', 'NEWDevOps',
       'NEWDevOpsImpt', 'NEWEdImpt', 'NEWJobHunt', 'NEWJobHuntResearch',
       'NEWLearn', 'NEWOffTopic', 'NEWOnboardGood', 'NEWOtherComms',
       'NEWOvertime', 'NEWPurchaseResearch', 'NEWPurpleLink', 'NEWSOSites',
       'NEWStuck', 'OpSys', 'OrgSize', 'PlatformDesireNextYear',
       'PlatformWorkedWith', 'PurchaseWhat', 'Sexuality', 'SOAccount',
       'SOComm', 'SOPartFreq', 'SOVisitFreq', 'SurveyEase', 'SurveyLength',
       'Trans', 'UndergradMajor', 'WebframeDesireNextYear',
       'WebframeWorkedWith', 'WelcomeChange', 'WorkWeekHrs', 'YearsCode',
       'YearsCodePro'],
      dtype='object')

In [39]:
df['LanguageWorkedWith']

0                    C#;HTML/CSS;JavaScript;SQL;TypeScript
1                                                      NaN
2                                                      NaN
3                                                      NaN
4                                                 Java;SQL
                               ...
16110                                                  NaN
16111                                                  NaN
16112                                           C;C++;Java
16113    Bash/Shell/PowerShell;HTML/CSS;JavaScript;Perl...
16114           C#;C++;HTML/CSS;Java;JavaScript;TypeScript
Name: LanguageWorkedWith, Length: 16115, dtype: object

In [45]:
df["LanguageWorkedWith"].str.contains("Python").value_counts()

False    7985
True     6340
Name: LanguageWorkedWith, dtype: int64

In [37]:
df["Country"].value_counts()

United States     3120
India             2112
Germany            977
United Kingdom     971
Canada             562
                  ...
Burkina Faso         1
Swaziland            1
San Marino           1
Haiti                1
Belize               1
Name: Country, Length: 165, dtype: int64

In [4]:
df.head()

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
0,63311,I am a developer by profession,Yes,27.0,16,Monthly,40000.0,109956.0,Brazil,Brazilian real,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;ASP.NET Core;Vue.js,Angular;ASP.NET Core,Just as welcome now as I felt last year,80.0,8,7
1,65180,I am a developer by profession,Yes,NaN,16,NaN,NaN,NaN,Dominican Republic,Dominican peso,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,NaN,6,3
2,42378,"I am not primarily a developer, but I write co...",No,NaN,12,NaN,NaN,NaN,United States,NaN,...,NaN,NaN,NaN,"Another engineering discipline (such as civil,...",NaN,NaN,NaN,NaN,35,25
3,42192,I am a developer by profession,Yes,NaN,15,NaN,NaN,NaN,Brazil,NaN,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,NaN,5,Less than 1 year
4,21072,I am a developer by profession,Yes,24.0,20,Monthly,16211.0,2712.0,India,Indian rupee,...,Neither easy nor difficult,Too long,No,"Computer science, computer engineering, or sof...",Angular;Spring,Angular;Spring,A lot more welcome now than last year,45.0,4,Less than 1 year

In [5]:
pd.set_option("display.max_columns", 60)

In [6]:
df.head()

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,...,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
0,63311,I am a developer by profession,Yes,27.0,16,Monthly,40000.0,109956.0,Brazil,Brazilian real,BRL,DynamoDB;Microsoft SQL Server;MongoDB;Redis,Microsoft SQL Server,"Developer, full-stack;DevOps specialist","Associate degree (A.A., A.S., etc.)","Independent contractor, freelancer, or self-em...",White or of European descent,Man,"Flex time or a flexible schedule;Languages, fr...",Slightly satisfied,"I’m not actively looking, but I am open to new...",C#;JavaScript;SQL,C#;HTML/CSS;JavaScript;SQL;TypeScript,.NET Core;Node.js;Unity 3D,.NET;.NET Core;Node.js;Unity 3D,Gitlab;Slack,Confluence;Jira;Github;Gitlab;Facebook Workpla...,No,Extremely important,Not at all important/not necessary,...,Company reviews from third party sites (e.g. G...,Every few months,Not sure,No,Yes,Sometimes: 1-2 days per month but less than we...,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,Windows,20 to 99 employees,AWS;Microsoft Azure;Slack Apps and Integrations,AWS;Docker;Microsoft Azure;Slack Apps and Inte...,NaN,Straight / Heterosexual,Yes,"Yes, somewhat",A few times per month or weekly,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;ASP.NET Core;Vue.js,Angular;ASP.NET Core,Just as welcome now as I felt last year,80.0,8,7
1,65180,I am a developer by profession,Yes,NaN,16,NaN,NaN,NaN,Dominican Republic,Dominican peso,DOP,NaN,NaN,"Developer, back-end",Some college/university study without earning ...,"Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,Very dissatisfied,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very important,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,NaN,6,3
2,42378,"I am not primarily a developer, but I write co...",No,NaN,12,NaN,NaN,NaN,United States,NaN,NaN,NaN,NaN,"Database administrator;Designer;Engineer, data",Some college/university study without earning ...,"Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not at all important/not necessary,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Another engineering discipline (such as civil,...",NaN,NaN,NaN,NaN,35,25
3,42192,I am a developer by profession,Yes,NaN,15,NaN,NaN,NaN,Brazil,NaN,NaN,NaN,NaN,"Academic researcher;Developer, full-stack;Deve...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed part-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very important,...,NaN,NaN,Not sure,NaN,No,NaN,NaN,NaN,Stack Overflow (public Q&A for anyone who code...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not sure/can't remember,Neutral,NaN,Multiple times per day,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,NaN,5,Less than 1 year
4,21072,I am a developer by profession,Yes,24.0,20,Monthly,16211.0,2712.0,India,Indian rupee,INR,MySQL;Oracle,MySQL;Oracle,"Developer, full-stack","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,Man,"Industry that I’d be working in;Languages, fra...",Very dissatisfied,I am actively looking for a job,Java;TypeScript,Java;SQL,Hadoop;Node.js;Xamarin,NaN,Jira;Github;Gitlab;Microsoft Teams;Microsoft A...,NaN,No,Extremely important,Not at all important/not necessary,...,"Read company media, such as employee blogs or ...",Every few months,Not sure,Onboarding? What onboarding?,No,Often: 1-2 days per week or more,Visit developer communities like Stack Overflow,Annoyed,Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow,Linux-based,10 to 19 employees,MacOS;Windows,Linux,I have some influence,NaN,Not sure/can't remember,Neutral,NaN,Multiple times per day,Neither easy nor difficult,Too long,No,"Computer science, computer engineering, or sof...",Angular;Spring,Angular;Spring,A lot more welcome now than last year,45.0,4,Less than 1 year

In [7]:
df_schema

                Column                                       QuestionText
0           Respondent  Randomized respondent ID number (not in order ...
1           MainBranch  Which of the following options best describes ...
2             Hobbyist                            Do you code as a hobby?
3                  Age  What is your age (in years)? If you prefer not...
4           Age1stCode  At what age did you write your first line of c...
..                 ...                                                ...
56  WebframeWorkedWith  Which web frameworks have you done extensive d...
57       WelcomeChange  Compared to last year, how welcome do you feel...
58         WorkWeekHrs  On average, how many hours per week do you wor...
59           YearsCode  Including any education, how many years have y...
60        YearsCodePro  NOT including education, how many years have y...

[61 rows x 2 columns]

In [8]:
df_schema[df_schema["Column"] == "ConvertedComp"]["QuestionText"].values

array(['Salary converted to annual USD salaries using the exchange rate on 2020-02-19, assuming 12 working months and 50 working weeks.'],
      dtype=object)

In [9]:
df["ConvertedComp"]

0        109956.0
1             NaN
2             NaN
3             NaN
4          2712.0
           ...
16110         NaN
16111         NaN
16112         NaN
16113         NaN
16114         NaN
Name: ConvertedComp, Length: 16115, dtype: float64

In [10]:
df_schema.set_index("Column", inplace=True)

In [11]:
df_schema

                                                         QuestionText
Column
Respondent          Randomized respondent ID number (not in order ...
MainBranch          Which of the following options best describes ...
Hobbyist                                      Do you code as a hobby?
Age                 What is your age (in years)? If you prefer not...
Age1stCode          At what age did you write your first line of c...
...                                                               ...
WebframeWorkedWith  Which web frameworks have you done extensive d...
WelcomeChange       Compared to last year, how welcome do you feel...
WorkWeekHrs         On average, how many hours per week do you wor...
YearsCode           Including any education, how many years have y...
YearsCodePro        NOT including education, how many years have y...

[61 rows x 1 columns]

In [12]:
df_schema.loc["Hobbyist"].values

array(['Do you code as a hobby?'], dtype=object)

In [13]:
df['Hobbyist'].count()

16107

In [14]:
df["Hobbyist"].value_counts()

Yes    12641
No      3466
Name: Hobbyist, dtype: int64

In [48]:
df[df["Country"] == "United States"]

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,...,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
2,42378,"I am not primarily a developer, but I write co...",No,NaN,12,NaN,NaN,NaN,United States,NaN,NaN,NaN,NaN,"Database administrator;Designer;Engineer, data",Some college/university study without earning ...,"Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not at all important/not necessary,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Another engineering discipline (such as civil,...",NaN,NaN,NaN,NaN,35,25
10,54515,I code primarily as a hobby,Yes,22.0,15,NaN,NaN,NaN,United States,NaN,NaN,Cassandra;Microsoft SQL Server;Oracle,Elasticsearch;Firebase;MySQL,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,Hispanic or Latino/a/x,Man,NaN,NaN,NaN,Go;Kotlin;Perl;PHP;Scala,C;C#;C++;HTML/CSS;Java;JavaScript;Objective-C;...,.NET;.NET Core;Flutter;Node.js;React Native,Xamarin,Facebook Workplace;Microsoft Teams;Microsoft A...,Github,NaN,NaN,NaN,...,NaN,Every few months,No,NaN,No,NaN,Visit developer communities like Stack Overflow,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow,MacOS,NaN,Android;Google Cloud Platform;Heroku;IBM Cloud...,Arduino;AWS;iOS;Linux;MacOS;Windows,NaN,Straight / Heterosexual,Yes,"Yes, somewhat",I have never participated in Q&A on Stack Over...,Daily or almost daily,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;Angular.js;ASP.NET;ASP.NET Core;React.js,jQuery;Ruby on Rails,Just as welcome now as I felt last year,NaN,3,NaN
12,3091,I am a developer by profession,Yes,NaN,20,Yearly,500000.0,500000.0,United States,United States dollar,USD,MongoDB,MongoDB,"Database administrator;Designer;Developer, bac...","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",White or of European descent,Man,"Languages, frameworks, and other technologies ...",Very satisfied,I am not interested in new job opportunities,Python,C#;Python,NaN,.NET Core;Xamarin,Github;Trello,Github;Trello,No,Neutral,Fairly important,...,"Read company media, such as employee blogs or ...",Once every few years,Yes,Yes,Yes,Occasionally: 1-2 days per quarter but less th...,Start a free trial;Ask developers I know/work ...,Amused,Stack Overflow (public Q&A for anyone who codes),Play games;Go for a walk or other physical act...,MacOS,2 to 9 employees,AWS;MacOS,AWS;MacOS,NaN,Straight / Heterosexual,Yes,"Yes, somewhat",A few times per week,A few times per week,Neither easy nor difficult,Appropriate in length,No,Mathematics or statistics,NaN,ASP.NET Core;Vue.js,Just as welcome now as I felt last year,40.0,25,22
14,49530,I am a developer by profession,Yes,46.0,12,Yearly,130000.0,130000.0,United States,United States dollar,USD,Microsoft SQL Server;MongoDB;MySQL;PostgreSQL;...,Microsoft SQL Server,"Database administrator;Developer, back-end;Dev...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,Flex time or a flexible schedule;Remote work o...,Slightly satisfied,"I’m not actively looking, but I am open to new...",C#;Go;JavaScript;Python;Ruby;TypeScript,C#;HTML/CSS;JavaScript;SQL;TypeScript,.NET;.NET Core;Node.js,.NET;.NET Core;Node.js,Microsoft Azure,"Github;Google Suite (Docs, Meet, etc)",No,Neutral,Fairly important,...,Company reviews from third party sites (e.g. G...,Once a year,Not sure,Onboarding? What onboarding?,No,Often: 1-2 days per week or more,Start a free trial;Ask developers I know/work ...,Indifferent,Stack Overflow (public Q&A for anyone who codes),Call a coworker or friend;Visit Stack Overflow...,Windows,2 to 9 employees,Android;Arduino;Linux;Microsoft Azure,NaN,I have a great deal of influence,Straight / Heterosexual,No,"No, not at all",NaN,Multiple times per day,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;ASP.NET Core,Angular;Angular.js;ASP.NET;ASP.NET Core;jQuery,Just as welcome now as I felt last year,45.0,34,24
17,50272,I am a developer by profession,No,62.0,12,Yearly,140000.0,140000.0,United States,United States dollar,USD,MySQL;Oracle,MySQL;Oracle,"Developer, back-end;Developer, desktop or ente...","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed full-time,White or of European descent,Man,Flex time or a flexible schedule;Office enviro...,Slightly satisfied,I am not interested in new job opportunities,Bash/Shell/PowerShell;Java;Perl;SQL,Bash/Shell/PowerShell;HTML/CSS;Java;Perl;SQL,NaN,NaN,Confluence;Jira;Slack,Confluence;Jira;Github;Slack,Not sure,Neutral,Fairly important,...,Company reviews from third party sites (e.g. G...,NaN,Not sure,No,No,Often: 1-2 days per week or more,NaN,Annoyed,Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Go for a walk or oth...,Linux-based,100 to 499 employees,Linux,Linux;MacOS,I have little or no influence,Gay or Lesbian,No,"No, not really",NaN,A few times per week,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,45.0,More than 50 years,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16089,20372,I am a developer by profession,No,26.0,18,Yearly,70000.0,70000.0,United States,United States dollar,USD,Couchbase;PostgreSQL;Redis;SQLite,DynamoDB;Elasticsearch;Firebase;MySQL;PostgreS...,"Developer, full-stack","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,Biracial,Man,"Languages, frameworks, and other technologies ...",Slightly satisfied,"I’m not actively looking, but I am open to new...",Bash/Shell/PowerShell;C#;C++;Go;HTML/CSS;Pytho...,Bash/Shell/PowerShell;C#;C++;HTML/CSS;JavaScri...,Node.js;React Native;Unity 3D,Node.js;React Native,"Github;Gitlab;Google Suite (Docs, Meet, etc)","Github;Gitlab;Slack;Google Suite (Docs, Meet, ...",No,Somewhat important,Fairly important,...,Personal network - friends or family,Once a year,Not sure,Onboarding? What onboarding?,No,Sometimes: 1-2 days per month but less than we...,Start a free trial;Visit developer communities...,"Hello, old friend",Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow;Go for a walk or other ph...,MacOS,20 to 99 employees,Docker;iOS;Kubernetes;Linux;MacOS;Windows,AWS;iOS;MacOS;Windows,I have some influence,Straight / Heterosexual,Not sure/can't remember,"No, not at all",NaN,A few times per month or weekly,Neither easy nor difficult,Too long,No,"Computer science, computer engineering, or sof...",Express;Gatsby;React.js;Ruby on Rails,Express;Gatsby;React.js;Ruby on Rails,Somewhat more welcome now than last year,45.0,9,5
16097,26042,I am a developer by profession,Yes,49.0,12,Yearly,220000.0,220000.0,United States,United States dollar,USD,MariaDB;PostgreSQL;Redis;SQLite,MariaDB;PostgreSQL;Redis;SQLite,Data scientist or machine learning specialist;...,"Other doctoral degree (Ph.D., Ed.D., etc.)",Employed full-time,White or of European descent,Man,"Languages, frameworks, and other technologies ...",Very satisfied,I am not interested in new job opportunities,Bash/Shell/PowerShell;C++;HTML/CSS;Python;SQL,Bash/Shell/PowerShell;C++;HTML/CSS;Python;SQL,Node.js;Pandas;Torch/PyTorch,.NET;Node.js;Torch/PyTorch,Github;Microsoft Teams;Microsoft Azure,Github;Microsoft Teams;Microsoft Azure,Yes,Extremely important,Very important,...,NaN,Every few months,Yes,Yes,No,Often: 1-2 days per week or more,Start a free trial;Visit developer communities...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Meditate;Visit Stack Overflow;Go for a walk or...,Linux-based,"10,000 or more employees",Docker;Kubernetes;Linux;Microsoft Azure,Docker;Kubernetes;Linux;Microsoft Azure;Windows,I have some influence,Straight / Heterosexual,Yes,"Yes, definitely",Less than once per month or monthly,Multiple times per day,Easy,Too short,No,"A natural science (such as biology, chemistry,...",Express;jQuery;Vue.js,Express;jQuery;Vue.js,Somewhat more welcome now than last year,55.0,35,12
16100,25290,I am a developer by profession,Yes,29.0,10,Yearly,74000.0,74000.0,United States,United States dollar,USD,MongoDB;Oracle,Oracle,"Developer, back-end;Developer, front-end;Devel...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Woman,Diversity of the company or organization;Flex ...,Slightly satisfied,"I’m not actively looking, but I am open to new...",C#;HTML/CSS;JavaScript;SQL;Swift;TypeScript,C#;HTML/CSS;JavaScript;TypeScript,.NET Core;Ansible;React Native,.NET;.NET Core;Node.js,Jira;Microsoft Teams;Stack Overflow for Teams,Jira;Slack;Microsoft Teams,Yes,Extremely important,Somewhat important,...,"Read company media, such as employee blogs or ...",Once a year,No,Yes,No,Rarely: 1-2 days per year or less,NaN,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Meditate;Play games;Call a coworker or friend;...,Windows,"10,000 or more employees",NaN,NaN,I have little or no influence,NaN,Yes,"Yes, somewhat",Less than once per month or monthly,A few times per month or weekly,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;ASP.NET Core,Angular;Angular.js;ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,40.0,12,7
16101,84,I am a developer by profession,Yes,25.0,12,Monthly,NaN,NaN,United States,United States dollar,USD,NaN,Oracle;PostgreSQL,"Developer, back-end;Developer, front-end;Devel...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,Flex time or a flexible schedule;Specific depa...,Slightly satisfied,"I’m not actively looking, but I am open to new...",NaN,Bash/Shell/PowerShell;C;C#;C++;HTML/CSS;Java;P...,NaN,.NET;.NET Core,NaN,Github;Slack;Microsoft Teams;Google Suite (Doc...,No,Neutral,Somewhat important,...,Directly asking current or past employees at t...,Once a year,Not sure,No,No,Often: 1-2 days per week or more,Start a free trial,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Do other work and come back later,Windows,2 to 9 employees,NaN,Android;Arduino;Linux;Raspberry Pi;Windows,I have some influence,Straight / Heterosexual,Yes,"No, not really",Less than once per month or monthly,Daily or almost daily,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,jQuery,Just as welcome now as I felt last year,60.0,13,2
16114,53862,I code primarily as a hobby,Yes,NaN,11,NaN,NaN,NaN,United States,NaN,NaN,PostgreSQL;SQLite,MariaDB;MySQL;PostgreSQL;SQLite,NaN,"Secondary school (e.g. American high school, G...",Student,Middle Eastern;White or of European descent;Bi...,Man,NaN,NaN,NaN,C#;C++;HTML/CSS;Java;JavaScript;Python;Ruby;SQL,C#;C++;HTML/CSS;Java;JavaScript;TypeScript,Node.js;React Native;TensorFlow;Unity 3D,Node.js,Gitlab;Trello,Github;Gitlab;Trello,NaN,NaN,NaN,...,NaN,Every few months,No,NaN,No,NaN,Ask developers I know/work with;Visit develope...,Annoyed,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Do other work and come ba...,Linux-based,NaN,Docker;Linux;Raspberry Pi,Linux;Raspberry Pi,NaN,Gay or Lesbian,Yes,Not sure,I have never participated in Q&A on Stack Over...,Daily or almost daily,Easy,Appropriate in length,No,NaN,Angular;Angular.js;Express;React.js;Vue.js,Express,Just as welcome now as I felt last year,NaN,5,NaN

### Grouping

In [49]:
country_grp = df.groupby(["Country"])

In [53]:
country_grp.get_group("Bangladesh")

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,...,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
35,14374,I am a developer by profession,No,28.0,20,Monthly,39000.0,5508.0,Bangladesh,Bangladeshi taka,BDT,Microsoft SQL Server;MongoDB,Microsoft SQL Server,"Developer, full-stack","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,South Asian,Man,Industry that I’d be working in;Office environ...,Neither satisfied nor dissatisfied,"I’m not actively looking, but I am open to new...",C#;HTML/CSS;JavaScript;TypeScript,C#;HTML/CSS;JavaScript,.NET Core;React Native;Xamarin,.NET,Jira;Github,Trello,No,Neutral,Not at all important/not necessary,...,"Read company media, such as employee blogs or ...",Every few months,Not sure,No,No,Sometimes: 1-2 days per month but less than we...,NaN,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Panic;Watch help / tutori...,Windows,2 to 9 employees,AWS;Linux;Microsoft Azure;Windows,Microsoft Azure;Windows,I have little or no influence,Straight / Heterosexual,Yes,"Yes, somewhat",Less than once per month or monthly,Multiple times per day,Easy,Appropriate in length,NaN,"Computer science, computer engineering, or sof...",Angular;ASP.NET Core;React.js;Vue.js,ASP.NET;jQuery,Somewhat more welcome now than last year,8.0,6,2
41,8337,"I used to be a developer by profession, but no...",Yes,26.0,19,NaN,NaN,NaN,Bangladesh,NaN,NaN,MongoDB;MySQL;Redis,MongoDB;MySQL;Redis,"Academic researcher;Developer, back-end;Develo...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,South Asian,Man,NaN,NaN,NaN,C;C++;Go;PHP;Python;SQL,C;C++;HTML/CSS;Java;JavaScript;PHP;SQL,Hadoop;Node.js;TensorFlow,Node.js,Github;Gitlab;Facebook Workplace;Trello;Google...,Jira;Github;Gitlab;Facebook Workplace;Slack;Tr...,NaN,NaN,Fairly important,...,NaN,Once a year,Yes,NaN,No,NaN,Start a free trial;Visit developer communities...,Amused,Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,Windows,NaN,Android;Google Cloud Platform;Linux;Windows,Android;Arduino;Google Cloud Platform;IBM Clou...,NaN,NaN,Yes,"Yes, somewhat",I have never participated in Q&A on Stack Over...,Daily or almost daily,Neither easy nor difficult,Too long,No,"Computer science, computer engineering, or sof...",Django;Express;jQuery;Laravel;Vue.js,Express;jQuery;Laravel;Vue.js,Just as welcome now as I felt last year,NaN,6,2
503,55272,I am a developer by profession,Yes,31.0,15,Monthly,30000.0,4236.0,Bangladesh,Bangladeshi taka,BDT,Firebase;MySQL,MySQL,"Designer;Developer, back-end;Developer, front-...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,Man,Opportunities for professional development,Very dissatisfied,I am actively looking for a job,Dart;Go;JavaScript;PHP;Python;SQL,JavaScript;PHP;SQL,Flutter;Node.js,NaN,Github;Trello;Stack Overflow for Teams,Github;Trello,No,Somewhat important,Fairly important,...,"Read company media, such as employee blogs or ...",Once a year,Yes,No,No,Often: 1-2 days per week or more,Start a free trial,"Hello, old friend",Stack Overflow (public Q&A for anyone who codes),Play games;Visit Stack Overflow;Go for a walk ...,Windows,2 to 9 employees,Raspberry Pi,NaN,I have some influence,NaN,Yes,Not sure,Less than once per month or monthly,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Another engineering discipline (such as civil,...",Django;Express;jQuery;Laravel;Vue.js,Angular.js;jQuery;Laravel;React.js;Vue.js,A lot more welcome now than last year,NaN,7,5
707,43654,I am a developer by profession,Yes,25.0,19,NaN,NaN,NaN,Bangladesh,NaN,NaN,Elasticsearch;Firebase;MySQL;PostgreSQL;Redis;...,MySQL;SQLite,"Developer, full-stack","Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Not employed, but looking for work",East Asian,Man,How widely used or impactful my work output wo...,NaN,I am actively looking for a job,Go;HTML/CSS;JavaScript;PHP;Python;Rust;SQL;Typ...,HTML/CSS;JavaScript;PHP;SQL,Flutter;Node.js;React Native;TensorFlow,Node.js,Github;Trello,Github;Trello,NaN,NaN,Not at all important/not necessary,...,Company reviews from third party sites (e.g. G...,Every few months,Yes,NaN,Yes,NaN,Visit developer communities like Stack Overflo...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Watch help / tutorial videos,Windows,NaN,Android;Docker;Kubernetes;Linux;Windows,Windows,NaN,Straight / Heterosexual,Yes,Neutral,I have never participated in Q&A on Stack Over...,Multiple times per day,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Express;Gatsby;Laravel;React.js;Symfony;Vue.js,Express;Laravel;React.js,Just as welcome now as I felt last year,NaN,6,NaN
1034,5251,I am a student who is learning to code,Yes,21.0,16,NaN,NaN,NaN,Bangladesh,NaN,NaN,Firebase;MongoDB;MySQL;Oracle;PostgreSQL,Oracle;PostgreSQL,"Developer, back-end;Developer, front-end;Devel...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Not employed, but looking for work",Southeast Asian,Man,"Languages, frameworks, and other technologies ...",NaN,I am actively looking for a job,C++;Dart;Go;HTML/CSS;Java;JavaScript;Python;Ru...,C;C++;HTML/CSS;Java;JavaScript;Python;R;SQL,Flutter;Node.js;Pandas;React Native;TensorFlow...,NaN,Jira;Github;Gitlab;Microsoft Azure;Google Suit...,NaN,NaN,NaN,NaN,...,NaN,Every few months,Not sure,NaN,No,NaN,Start a free trial;Ask developers I know/work ...,Annoyed,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Watch help / tutorial vid...,Linux-based,NaN,Android;AWS;Docker;Google Cloud Platform;Herok...,Arduino;Linux,NaN,Straight / Heterosexual,Yes,"Yes, definitely",Multiple times per day,Multiple times per day,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;Angular.js;Express;React.js;Ruby on Ra...,NaN,Just as welcome now as I felt last year,NaN,4,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15960,5636,I am a developer by profession,Yes,27.0,6,Monthly,NaN,NaN,Bangladesh,Bangladeshi taka,BDT,MongoDB,MySQL,"Designer;Developer, back-end;Developer, deskto...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,South Asian,Man,Flex time or a flexible schedule;Remote work o...,Very satisfied,"I’m not actively looking, but I am open to new...",Dart;Go;Objective-C;TypeScript,Assembly;C;C++;HTML/CSS;JavaScript;PHP;Python;SQL,.NET;Flutter;Unity 3D;Xamarin,Node.js,Microsoft Teams;Microsoft Azure,Jira;Github;Gitlab;Facebook Workplace;Slack;Tr...,Yes,Somewhat important,Fairly important,...,Personal network - friends or family,Once a year,Yes,Yes,Yes,Sometimes: 1-2 days per month but less than we...,NaN,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow,Linux-based,2 to 9 employees,AWS;Docker;Google Cloud Platform;MacOS;Slack A...,Linux;WordPress,I have little or no influence,NaN,Yes,"Yes, definitely",Multiple times per day,Multiple times per day,Easy,Too long,No,"Computer science, computer engineering, or sof...",Angular;Angular.js;Gatsby;React.js,jQuery;Laravel;Vue.js,A lot more welcome now than last year,40.0,6,4
16001,34524,I am a student who is learning to code,Yes,21.0,16,NaN,NaN,NaN,Bangladesh,NaN,NaN,Microsoft SQL Server;MongoDB;SQLite,MySQL;Oracle,NaN,Primary/elementary school,Student,NaN,Man,"Languages, frameworks, and other technologies ...",NaN,I am actively looking for a job,C#;HTML/CSS;JavaScript;PHP;Python;Swift,Assembly;C;C++;Java;SQL,.NET;.NET Core;Node.js;React Native;Unity 3D;X...,NaN,Github;Gitlab;Facebook Workplace;Microsoft Tea...,NaN,NaN,NaN,NaN,...,NaN,Every few months,Yes,NaN,Yes,NaN,Start a free trial,Annoyed,Stack Overflow (public Q&A for anyone who codes),Play games;Visit Stack Overflow;Go for a walk ...,Windows,NaN,Android;iOS;Linux;MacOS;WordPress,Windows,NaN,NaN,Yes,Neutral,I have never participated in Q&A on Stack Over...,A few times per week,Neither easy nor difficult,Too long,NaN,NaN,ASP.NET;ASP.NET Core,NaN,A lot less welcome now than last year,NaN,2,NaN
16037,28769,I am a student who is learning to code,Yes,19.0,13,NaN,NaN,NaN,Bangladesh,NaN,NaN,MySQL,MySQL,"Developer, back-end;Developer, front-end;Devel...","Secondary school (e.g. American high school, G...","Not employed, but looking for work",Southeast Asian,Man,"Languages, frameworks, and other technologies ...",NaN,I am actively looking for a job,HTML/CSS;JavaScript;Python,C;C#;C++;HTML/CSS;Java;JavaScript;PHP;Python,NaN,Node.js;Unity 3D;Unreal Engine,Github,Github,NaN,NaN,NaN,...,NaN,Every few months,Yes,NaN,No,NaN,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who codes),Call a coworker or friend;Visit Stack Overflow...,Windows,NaN,WordPress,Arduino;Raspberry Pi;Windows,NaN,Straight / Heterosexual,Not sure/can't remember,Neutral,NaN,A few times per week,Neither easy nor difficult,Too long,No,NaN,Django;Flask;jQuery;React.js,NaN,Somewhat more welcome now than last year,NaN,5,NaN
16040,12666,I am a developer by profession,Yes,23.0,18,Monthly,7000.0,984.0,Bangladesh,Bangladeshi taka,BDT,Firebase;MariaDB;Microsoft SQL Server;MongoDB;...,Firebase;MariaDB;Microsoft SQL Server;MongoDB;...,"Developer, back-end;Developer, full-stack","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,South Asian,Man,"Languages, frameworks, and other technologies ...",Slightly dissatisfied,"I’m not actively looking, but I am open to new...",C#;HTML/CSS;Java;JavaScript;Python;SQL;TypeScript,C;C#;C++;HTML/CSS;Java;JavaScript;Python;Ruby;...,.NET;.NET Core;Apache Spark;Flutter;Hadoop;Nod...,Node.js;Pandas,Jira;Github;Facebook Workplace;Microsoft Azure...,"Github;Trello;Google Suite (Docs, Meet, etc)",No,Extremely important,Somewhat important,...,"Read company media, such as employee blogs or ...",Every few months,No,No,Yes,Often: 1-2 days per week or more,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who codes),Play games;Call a coworker or friend;Visit Sta...,Windows,10 to 19 employees,Android;Docker;Google Cloud Platform;Heroku;Li...,Android;Heroku;Linux;MacOS;Windows,I have some influence,Straight / Heterosexual,Yes,"Yes, definitely",I have never participated in Q&A on Stack Over...,Multiple times per day,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;ASP.NET;ASP.NET Core;Django;Express;Re...,Angular;Angular.js;ASP.NET;Django;Express;Flas...,Just as welcome now as I felt last year,48.0,5,Less than 1 year
16048,23192,I am a developer by profession,No,38.0,19,Monthly,85000.0,12012.0,Bangladesh,Bangladeshi taka,BDT,DynamoDB;Elasticsearch;Firebase;MariaDB;MongoD...,Firebase;MariaDB;MongoDB;MySQL;Redis;SQLite,"Developer, full-stack","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,South Asian,Man,Flex time or a flexible schedule;Office enviro...,Very dissatisfied,"I’m not actively looking, but I am open to new...",C++;Go;HTML/CSS;Java;JavaScript;PHP;Python;SQL...,C;C++;HTML/CSS;Java;JavaScript;PHP;Python;SQL;...,Node.js,Node.js;React Native,Github;Gitlab;Slack,Github;Gitlab;Slack,No,Extremely important,Somewhat important,...,Personal network - friends or family;Read othe...,Every few months,No,No,No,Often: 1-2 days per week or more,Start a free trial;Ask developers I know/work ...,Annoyed,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow,Windows,20 to 99 employees,Android;Docker;Kubernetes;Windows,Android;Heroku;Windows,I have some influence,Straight / Heterosexual,Yes,"Yes, definitely",A few times per month or weekly,Multiple times per day,Neither easy nor difficult,Too long,No,"Computer science, computer engineering, or sof...",Angular;Django;Express;jQuery;Laravel;React.js...,Angular;Django;Express;jQuery;Laravel;React.js...,Just as welcome now as I felt last year,NaN,17,NaN

In [55]:
country_grp["LanguageWorkedWith"].get_group("Bangladesh")

35                                  C#;HTML/CSS;JavaScript
41                  C;C++;HTML/CSS;Java;JavaScript;PHP;SQL
503                                     JavaScript;PHP;SQL
707                            HTML/CSS;JavaScript;PHP;SQL
1034           C;C++;HTML/CSS;Java;JavaScript;Python;R;SQL
                               ...
15960    Assembly;C;C++;HTML/CSS;JavaScript;PHP;Python;SQL
16001                              Assembly;C;C++;Java;SQL
16037         C;C#;C++;HTML/CSS;Java;JavaScript;PHP;Python
16040    C;C#;C++;HTML/CSS;Java;JavaScript;Python;Ruby;...
16048    C;C++;HTML/CSS;Java;JavaScript;PHP;Python;SQL;...
Name: LanguageWorkedWith, Length: 130, dtype: object

In [16]:
df["Country"].value_counts()

United States     3120
India             2112
Germany            977
United Kingdom     971
Canada             562
                  ...
Burkina Faso         1
Swaziland            1
San Marino           1
Haiti                1
Belize               1
Name: Country, Length: 165, dtype: int64

In [17]:
country_grp.get_group("United States")

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,...,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
2,42378,"I am not primarily a developer, but I write co...",No,NaN,12,NaN,NaN,NaN,United States,NaN,NaN,NaN,NaN,"Database administrator;Designer;Engineer, data",Some college/university study without earning ...,"Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not at all important/not necessary,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Another engineering discipline (such as civil,...",NaN,NaN,NaN,NaN,35,25
10,54515,I code primarily as a hobby,Yes,22.0,15,NaN,NaN,NaN,United States,NaN,NaN,Cassandra;Microsoft SQL Server;Oracle,Elasticsearch;Firebase;MySQL,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,Hispanic or Latino/a/x,Man,NaN,NaN,NaN,Go;Kotlin;Perl;PHP;Scala,C;C#;C++;HTML/CSS;Java;JavaScript;Objective-C;...,.NET;.NET Core;Flutter;Node.js;React Native,Xamarin,Facebook Workplace;Microsoft Teams;Microsoft A...,Github,NaN,NaN,NaN,...,NaN,Every few months,No,NaN,No,NaN,Visit developer communities like Stack Overflow,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow,MacOS,NaN,Android;Google Cloud Platform;Heroku;IBM Cloud...,Arduino;AWS;iOS;Linux;MacOS;Windows,NaN,Straight / Heterosexual,Yes,"Yes, somewhat",I have never participated in Q&A on Stack Over...,Daily or almost daily,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;Angular.js;ASP.NET;ASP.NET Core;React.js,jQuery;Ruby on Rails,Just as welcome now as I felt last year,NaN,3,NaN
12,3091,I am a developer by profession,Yes,NaN,20,Yearly,500000.0,500000.0,United States,United States dollar,USD,MongoDB,MongoDB,"Database administrator;Designer;Developer, bac...","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",White or of European descent,Man,"Languages, frameworks, and other technologies ...",Very satisfied,I am not interested in new job opportunities,Python,C#;Python,NaN,.NET Core;Xamarin,Github;Trello,Github;Trello,No,Neutral,Fairly important,...,"Read company media, such as employee blogs or ...",Once every few years,Yes,Yes,Yes,Occasionally: 1-2 days per quarter but less th...,Start a free trial;Ask developers I know/work ...,Amused,Stack Overflow (public Q&A for anyone who codes),Play games;Go for a walk or other physical act...,MacOS,2 to 9 employees,AWS;MacOS,AWS;MacOS,NaN,Straight / Heterosexual,Yes,"Yes, somewhat",A few times per week,A few times per week,Neither easy nor difficult,Appropriate in length,No,Mathematics or statistics,NaN,ASP.NET Core;Vue.js,Just as welcome now as I felt last year,40.0,25,22
14,49530,I am a developer by profession,Yes,46.0,12,Yearly,130000.0,130000.0,United States,United States dollar,USD,Microsoft SQL Server;MongoDB;MySQL;PostgreSQL;...,Microsoft SQL Server,"Database administrator;Developer, back-end;Dev...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,Flex time or a flexible schedule;Remote work o...,Slightly satisfied,"I’m not actively looking, but I am open to new...",C#;Go;JavaScript;Python;Ruby;TypeScript,C#;HTML/CSS;JavaScript;SQL;TypeScript,.NET;.NET Core;Node.js,.NET;.NET Core;Node.js,Microsoft Azure,"Github;Google Suite (Docs, Meet, etc)",No,Neutral,Fairly important,...,Company reviews from third party sites (e.g. G...,Once a year,Not sure,Onboarding? What onboarding?,No,Often: 1-2 days per week or more,Start a free trial;Ask developers I know/work ...,Indifferent,Stack Overflow (public Q&A for anyone who codes),Call a coworker or friend;Visit Stack Overflow...,Windows,2 to 9 employees,Android;Arduino;Linux;Microsoft Azure,NaN,I have a great deal of influence,Straight / Heterosexual,No,"No, not at all",NaN,Multiple times per day,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;ASP.NET Core,Angular;Angular.js;ASP.NET;ASP.NET Core;jQuery,Just as welcome now as I felt last year,45.0,34,24
17,50272,I am a developer by profession,No,62.0,12,Yearly,140000.0,140000.0,United States,United States dollar,USD,MySQL;Oracle,MySQL;Oracle,"Developer, back-end;Developer, desktop or ente...","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed full-time,White or of European descent,Man,Flex time or a flexible schedule;Office enviro...,Slightly satisfied,I am not interested in new job opportunities,Bash/Shell/PowerShell;Java;Perl;SQL,Bash/Shell/PowerShell;HTML/CSS;Java;Perl;SQL,NaN,NaN,Confluence;Jira;Slack,Confluence;Jira;Github;Slack,Not sure,Neutral,Fairly important,...,Company reviews from third party sites (e.g. G...,NaN,Not sure,No,No,Often: 1-2 days per week or more,NaN,Annoyed,Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Go for a walk or oth...,Linux-based,100 to 499 employees,Linux,Linux;MacOS,I have little or no influence,Gay or Lesbian,No,"No, not really",NaN,A few times per week,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,45.0,More than 50 years,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16089,20372,I am a developer by profession,No,26.0,18,Yearly,70000.0,70000.0,United States,United States dollar,USD,Couchbase;PostgreSQL;Redis;SQLite,DynamoDB;Elasticsearch;Firebase;MySQL;PostgreS...,"Developer, full-stack","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,Biracial,Man,"Languages, frameworks, and other technologies ...",Slightly satisfied,"I’m not actively looking, but I am open to new...",Bash/Shell/PowerShell;C#;C++;Go;HTML/CSS;Pytho...,Bash/Shell/PowerShell;C#;C++;HTML/CSS;JavaScri...,Node.js;React Native;Unity 3D,Node.js;React Native,"Github;Gitlab;Google Suite (Docs, Meet, etc)","Github;Gitlab;Slack;Google Suite (Docs, Meet, ...",No,Somewhat important,Fairly important,...,Personal network - friends or family,Once a year,Not sure,Onboarding? What onboarding?,No,Sometimes: 1-2 days per month but less than we...,Start a free trial;Visit developer communities...,"Hello, old friend",Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow;Go for a walk or other ph...,MacOS,20 to 99 employees,Docker;iOS;Kubernetes;Linux;MacOS;Windows,AWS;iOS;MacOS;Windows,I have some influence,Straight / Heterosexual,Not sure/can't remember,"No, not at all",NaN,A few times per month or weekly,Neither easy nor difficult,Too long,No,"Computer science, computer engineering, or sof...",Express;Gatsby;React.js;Ruby on Rails,Express;Gatsby;React.js;Ruby on Rails,Somewhat more welcome now than last year,45.0,9,5
16097,26042,I am a developer by profession,Yes,49.0,12,Yearly,220000.0,220000.0,United States,United States dollar,USD,MariaDB;PostgreSQL;Redis;SQLite,MariaDB;PostgreSQL;Redis;SQLite,Data scientist or machine learning specialist;...,"Other doctoral degree (Ph.D., Ed.D., etc.)",Employed full-time,White or of European descent,Man,"Languages, frameworks, and other technologies ...",Very satisfied,I am not interested in new job opportunities,Bash/Shell/PowerShell;C++;HTML/CSS;Python;SQL,Bash/Shell/PowerShell;C++;HTML/CSS;Python;SQL,Node.js;Pandas;Torch/PyTorch,.NET;Node.js;Torch/PyTorch,Github;Microsoft Teams;Microsoft Azure,Github;Microsoft Teams;Microsoft Azure,Yes,Extremely important,Very important,...,NaN,Every few months,Yes,Yes,No,Often: 1-2 days per week or more,Start a free trial;Visit developer communities...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Meditate;Visit Stack Overflow;Go for a walk or...,Linux-based,"10,000 or more employees",Docker;Kubernetes;Linux;Microsoft Azure,Docker;Kubernetes;Linux;Microsoft Azure;Windows,I have some influence,Straight / Heterosexual,Yes,"Yes, definitely",Less than once per month or monthly,Multiple times per day,Easy,Too short,No,"A natural science (such as biology, chemistry,...",Express;jQuery;Vue.js,Express;jQuery;Vue.js,Somewhat more welcome now than last year,55.0,35,12
16100,25290,I am a developer by profession,Yes,29.0,10,Yearly,74000.0,74000.0,United States,United States dollar,USD,MongoDB;Oracle,Oracle,"Developer, back-end;Developer, front-end;Devel...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Woman,Diversity of the company or organization;Flex ...,Slightly satisfied,"I’m not actively looking, but I am open to new...",C#;HTML/CSS;JavaScript;SQL;Swift;TypeScript,C#;HTML/CSS;JavaScript;TypeScript,.NET Core;Ansible;React Native,.NET;.NET Core;Node.js,Jira;Microsoft Teams;Stack Overflow for Teams,Jira;Slack;Microsoft Teams,Yes,Extremely important,Somewhat important,...,"Read company media, such as employee blogs or ...",Once a year,No,Yes,No,Rarely: 1-2 days per year or less,NaN,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Meditate;Play games;Call a coworker or friend;...,Windows,"10,000 or more employees",NaN,NaN,I have little or no influence,NaN,Yes,"Yes, somewhat",Less than once per month or monthly,A few times per month or weekly,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;ASP.NET Core,Angular;Angular.js;ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,40.0,12,7
16101,84,I am a developer by profession,Yes,25.0,12,Monthly,NaN,NaN,United States,United States dollar,USD,NaN,Oracle;PostgreSQL,"Developer, back-end;Developer, front-end;Devel...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,Flex time or a flexible schedule;Specific depa...,Slightly satisfied,"I’m not actively looking, but I am open to new...",NaN,Bash/Shell/PowerShell;C;C#;C++;HTML/CSS;Java;P...,NaN,.NET;.NET Core,NaN,Github;Slack;Microsoft Teams;Google Suite (Doc...,No,Neutral,Somewhat important,...,Directly asking current or past employees at t...,Once a year,Not sure,No,No,Often: 1-2 days per week or more,Start a free trial,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Do other work and come back later,Windows,2 to 9 employees,NaN,Android;Arduino;Linux;Raspberry Pi;Windows,I have some influence,Straight / Heterosexual,Yes,"No, not really",Less than once per month or monthly,Daily or almost daily,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,jQuery,Just as welcome now as I felt last year,60.0,13,2
16114,53862,I code primarily as a hobby,Yes,NaN,11,NaN,NaN,NaN,United States,NaN,NaN,PostgreSQL;SQLite,MariaDB;MySQL;PostgreSQL;SQLite,NaN,"Secondary school (e.g. American high school, G...",Student,Middle Eastern;White or of European descent;Bi...,Man,NaN,NaN,NaN,C#;C++;HTML/CSS;Java;JavaScript;Python;Ruby;SQL,C#;C++;HTML/CSS;Java;JavaScript;TypeScript,Node.js;React Native;TensorFlow;Unity 3D,Node.js,Gitlab;Trello,Github;Gitlab;Trello,NaN,NaN,NaN,...,NaN,Every few months,No,NaN,No,NaN,Ask developers I know/work with;Visit develope...,Annoyed,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Do other work and come ba...,Linux-based,NaN,Docker;Linux;Raspberry Pi,Linux;Raspberry Pi,NaN,Gay or Lesbian,Yes,Not sure,I have never participated in Q&A on Stack Over...,Daily or almost daily,Easy,Appropriate in length,No,NaN,Angular;Angular.js;Express;React.js;Vue.js,Express,Just as welcome now as I felt last year,NaN,5,NaN

In [67]:
country_grp["LanguageWorkedWith"].apply(lambda x: x.str.contains("Python").sum())

Country
Afghanistan                              5
Albania                                  1
Algeria                                 13
Andorra                                  0
Angola                                   0
                                        ..
Venezuela, Bolivarian Republic of...     9
Viet Nam                                19
Yemen                                    0
Zambia                                   1
Zimbabwe                                 2
Name: LanguageWorkedWith, Length: 165, dtype: int64

In [18]:
df_schema.loc["NEWCollabToolsDesireNextYear"].values

array(['Which collaboration tools have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you worked with the tool and want to continue to do so, please check both boxes in that row.)'],
      dtype=object)

In [19]:
# grouping by filter
filt = df['Country']=='Bangladesh'
df.loc[filt]['NEWCollabToolsDesireNextYear'].value_counts()

Github                                                                                   12
Github;Stack Overflow for Teams                                                           3
Github;Trello                                                                             3
Gitlab                                                                                    3
Jira;Github;Gitlab;Google Suite (Docs, Meet, etc)                                         2
                                                                                         ..
Github;Gitlab;Facebook Workplace;Trello;Google Suite (Docs, Meet, etc)                    1
Github;Microsoft Teams;Trello;Google Suite (Docs, Meet, etc);Stack Overflow for Teams     1
Jira;Github;Slack;Google Suite (Docs, Meet, etc);Stack Overflow for Teams                 1
Jira;Github;Slack                                                                         1
Github;Gitlab;Slack                                                                       1
Name: NEWCollabToolsDesireNextYear, Length: 61, dtype: int64

In [58]:
country_grp['Employment'].value_counts()

Country      Employment
Afghanistan  Employed full-time                                      9
             Employed part-time                                      3
             Independent contractor, freelancer, or self-employed    3
             Student                                                 2
             Not employed, but looking for work                      1
                                                                    ..
Zambia       Independent contractor, freelancer, or self-employed    1
Zimbabwe     Employed full-time                                      2
             Employed part-time                                      2
             Independent contractor, freelancer, or self-employed    1
             Student                                                 1
Name: Employment, Length: 614, dtype: int64

In [63]:
country_grp['Employment'].value_counts().head(50)

Country      Employment
Afghanistan  Employed full-time                                        9
             Employed part-time                                        3
             Independent contractor, freelancer, or self-employed      3
             Student                                                   2
             Not employed, but looking for work                        1
Albania      Employed full-time                                        6
             Not employed, but looking for work                        1
Algeria      Employed full-time                                        8
             Student                                                   6
             Employed part-time                                        4
             Independent contractor, freelancer, or self-employed      3
             Not employed, but looking for work                        2
Andorra      Independent contractor, freelancer, or self-employed      1
Angola       Employed full-time                                        1
             Not employed, but looking for work                        1
             Student                                                   1
Argentina    Employed full-time                                       51
             Independent contractor, freelancer, or self-employed     14
             Student                                                   6
             Employed part-time                                        4
             Not employed, but looking for work                        4
Armenia      Employed full-time                                        8
             Independent contractor, freelancer, or self-employed      2
             Employed part-time                                        1
Australia    Employed full-time                                      236
             Student                                                  30
             Independent contractor, freelancer, or self-employed     25
             Not employed, but looking for work                       13
             Employed part-time                                       12
             Retired                                                   2
             Not employed, and not looking for work                    1
Austria      Employed full-time                                       68
             Student                                                  23
             Employed part-time                                       19
             Independent contractor, freelancer, or self-employed     14
             Not employed, but looking for work                        2
Azerbaijan   Employed full-time                                        8
             Student                                                   4
             Employed part-time                                        1
             Not employed, but looking for work                        1
Bahamas      Independent contractor, freelancer, or self-employed      1
Bahrain      Employed full-time                                        4
Bangladesh   Employed full-time                                       68
             Student                                                  24
             Not employed, but looking for work                       17
             Independent contractor, freelancer, or self-employed     12
             Employed part-time                                        5
Barbados     Employed full-time                                        1
Belarus      Employed full-time                                       22
             Independent contractor, freelancer, or self-employed      8
Name: Employment, dtype: int64

In [21]:
country_grp['ConvertedComp'].median().loc['Germany']

64859.0

### aggrigation

In [22]:
country_grp['ConvertedComp'].agg(['median', 'mean'])

                                       median          mean
Country
Afghanistan                           13199.0  52174.500000
Albania                               10704.0  13296.000000
Algeria                               14400.0  14400.000000
Andorra                                   NaN           NaN
Angola                                 5736.0   5736.000000
...                                       ...           ...
Venezuela, Bolivarian Republic of...   4800.0   7482.785714
Viet Nam                              10086.0  22873.600000
Yemen                                 36000.0  36000.000000
Zambia                                 1632.0   1632.000000
Zimbabwe                              90600.0  90600.000000

[165 rows x 2 columns]

In [23]:
country_grp['ConvertedComp'].agg(['median', 'mean']).loc['Canada']

median     65799.000000
mean      102923.195195
Name: Canada, dtype: float64

In [24]:
filt = df['Country']=='Bangladesh'
df.loc[filt]['LanguageWorkedWith'].str.contains('Python').sum()

41

In [25]:
df.loc[filt]['Employment'].str.contains('Student').value_counts()

False    102
True      24
Name: Employment, dtype: int64

In [26]:
country_usg_python = country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

In [27]:
country_usg_python

Country
Afghanistan                              5
Albania                                  1
Algeria                                 13
Andorra                                  0
Angola                                   0
                                        ..
Venezuela, Bolivarian Republic of...     9
Viet Nam                                19
Yemen                                    0
Zambia                                   1
Zimbabwe                                 2
Name: LanguageWorkedWith, Length: 165, dtype: int64

#### Quetion: Find the repondent country Name??

In [74]:
python_lang = country_grp["LanguageWorkedWith"].apply(lambda x: x.str.contains("Python").sum())

In [73]:
country_respondent = df['Country'].value_counts()

In [75]:
country_respondent

United States     3120
India             2112
Germany            977
United Kingdom     971
Canada             562
                  ...
Burkina Faso         1
Swaziland            1
San Marino           1
Haiti                1
Belize               1
Name: Country, Length: 165, dtype: int64

In [76]:
python_df = pd.concat([country_respondent, python_lang], axis='columns', sort=False)

In [77]:
python_df

                Country  LanguageWorkedWith
United States      3120                1505
India              2112                 680
Germany             977                 417
United Kingdom      971                 394
Canada              562                 267
...                 ...                 ...
Burkina Faso          1                   1
Swaziland             1                   1
San Marino            1                   0
Haiti                 1                   0
Belize                1                   1

[165 rows x 2 columns]

In [78]:
python_df.rename(columns={'Country':'NumRespondent', 'LanguageWorkedWith':'KnowsPython'}, inplace=True)

In [79]:
python_df

                NumRespondent  KnowsPython
United States            3120         1505
India                    2112          680
Germany                   977          417
United Kingdom            971          394
Canada                    562          267
...                       ...          ...
Burkina Faso                1            1
Swaziland                   1            1
San Marino                  1            0
Haiti                       1            0
Belize                      1            1

[165 rows x 2 columns]

In [81]:
java_script_usr = country_grp["LanguageWorkedWith"].apply(lambda x: x.str.contains("JavaScript").sum())
java_script_usr

Country
Afghanistan                             10
Albania                                  4
Algeria                                 15
Andorra                                  1
Angola                                   1
                                        ..
Venezuela, Bolivarian Republic of...    14
Viet Nam                                41
Yemen                                    2
Zambia                                   2
Zimbabwe                                 3
Name: LanguageWorkedWith, Length: 165, dtype: int64

In [85]:
java_script_df = pd.concat([country_respondent, java_script_usr], axis='columns', sort=False)
java_script_df.rename(columns={"Country": "Respondent", "LanguageWorkedWith": "JavaScript"}, inplace=True)

In [86]:
java_script_df

                Respondent  JavaScript
United States         3120        2001
India                 2112        1112
Germany                977         574
United Kingdom         971         609
Canada                 562         365
...                    ...         ...
Burkina Faso             1           0
Swaziland                1           0
San Marino               1           1
Haiti                    1           0
Belize                   1           1

[165 rows x 2 columns]

In [111]:
df["Country"].unique()

array(['Brazil', 'Dominican Republic', 'United States', 'India',
       'Portugal', 'Germany', 'Ireland', 'United Kingdom', 'Spain',
       'Sudan', 'Switzerland', 'Netherlands', 'Turkey', 'Australia',
       'Mexico', 'Israel', 'France', 'Serbia', 'Bangladesh', 'Iran',
       'Norway', nan, 'Greece', 'Canada', 'Sri Lanka', 'Romania',
       'Russian Federation', 'Poland', 'Colombia', 'Slovenia', 'Pakistan',
       'Bolivia', 'Finland', 'Ukraine', 'Nigeria', 'Denmark', 'Algeria',
       'Belgium', 'Japan', 'Georgia', 'Lebanon', 'Nepal', 'Singapore',
       'Solomon Islands', 'Kenya', 'Thailand', 'Malaysia', 'Sweden',
       'Costa Rica', 'Hungary', 'Mozambique', 'United Arab Emirates',
       'Estonia', 'Czech Republic', 'Kazakhstan', 'Croatia',
       'New Zealand', 'Lithuania', 'Italy', 'China', 'Indonesia',
       'Belarus', 'Morocco', 'Paraguay', 'Ghana', 'South Korea',
       'Viet Nam', 'Austria', 'South Africa', 'Egypt', 'Chile',
       'Saudi Arabia', 'Malawi', 'Somalia', 'Nicaragua', 'Slovakia',
       'Maldives', 'Democratic Republic of the Congo', 'Taiwan',
       'Republic of Moldova', 'Hong Kong (S.A.R.)', 'Argentina', 'Malta',
       'Philippines', 'Peru', 'Rwanda', 'Myanmar', 'El Salvador',
       'Jordan', 'Bulgaria', 'Venezuela, Bolivarian Republic of...',
       'Senegal', 'Cyprus', 'Bosnia and Herzegovina', 'Uruguay',
       'Timor-Leste', 'Azerbaijan', 'Albania', 'Kyrgyzstan', 'Ecuador',
       "Lao People's Democratic Republic", 'Latvia', 'Uganda', 'Mongolia',
       'Kosovo', 'Tunisia', 'Afghanistan', 'United Republic of Tanzania',
       'Armenia', 'Bhutan', 'Iraq', 'Zimbabwe',
       'The former Yugoslav Republic of Macedonia', 'Jamaica',
       'Republic of Korea', 'Uzbekistan', 'Benin', 'Honduras', 'Ethiopia',
       'Zambia', 'Turkmenistan', 'Qatar', 'Burundi', 'Swaziland', 'Togo',
       "Côte d'Ivoire", 'Cameroon', 'Guatemala', 'Yemen', 'Haiti',
       'Andorra', 'Panama', 'Oman', 'Libyan Arab Jamahiriya',
       'Sierra Leone', 'Nomadic', 'Cuba', 'Congo, Republic of the...',
       'San Marino', 'Mauritius', 'Iceland', 'Burkina Faso', 'Namibia',
       'Angola', 'Guinea', 'Bahrain', 'Cambodia', 'Cape Verde',
       'Montenegro', 'Tajikistan', 'Luxembourg', 'Nauru', 'Kuwait',
       'Eritrea', 'Brunei Darussalam', 'Syrian Arab Republic', 'Gambia',
       'Madagascar', 'Isle of Man', 'Barbados', 'Mali',
       'Antigua and Barbuda', 'Micronesia, Federated States of...',
       'Bahamas', 'Saint Vincent and the Grenadines', 'Belize'],
      dtype=object)

In [118]:
students = {}
for country in df["Country"].unique():
    try:
        student_num = (country_grp["Employment"].get_group(country)=="Student").sum()
        students[country] = student_num
    except:
        pass

In [119]:
students

{'Brazil': 31,
 'Dominican Republic': 0,
 'United States': 266,
 'India': 339,
 'Portugal': 14,
 'Germany': 143,
 'Ireland': 7,
 'United Kingdom': 76,
 'Spain': 28,
 'Sudan': 2,
 'Switzerland': 19,
 'Netherlands': 43,
 'Turkey': 28,
 'Australia': 30,
 'Mexico': 13,
 'Israel': 17,
 'France': 64,
 'Serbia': 7,
 'Bangladesh': 24,
 'Iran': 10,
 'Norway': 11,
 'Greece': 15,
 'Canada': 80,
 'Sri Lanka': 16,
 'Romania': 12,
 'Russian Federation': 14,
 'Poland': 31,
 'Colombia': 4,
 'Slovenia': 7,
 'Pakistan': 33,
 'Bolivia': 1,
 'Finland': 8,
 'Ukraine': 12,
 'Nigeria': 28,
 'Denmark': 11,
 'Algeria': 6,
 'Belgium': 11,
 'Japan': 4,
 'Georgia': 4,
 'Lebanon': 6,
 'Nepal': 12,
 'Singapore': 12,
 'Solomon Islands': 0,
 'Kenya': 19,
 'Thailand': 6,
 'Malaysia': 8,
 'Sweden': 28,
 'Costa Rica': 0,
 'Hungary': 10,
 'Mozambique': 0,
 'United Arab Emirates': 0,
 'Estonia': 1,
 'Czech Republic': 16,
 'Kazakhstan': 0,
 'Croatia': 5,
 'New Zealand': 6,
 'Lithuania': 4,
 'Italy': 34,
 'China': 32,
 'Indonesia': 23,
 'Belarus': 2,
 'Morocco': 15,
 'Paraguay': 1,
 'Ghana': 11,
 'South Korea': 7,
 'Viet Nam': 24,
 'Austria': 23,
 'South Africa': 14,
 'Egypt': 4,
 'Chile': 4,
 'Saudi Arabia': 3,
 'Malawi': 0,
 'Somalia': 3,
 'Nicaragua': 0,
 'Slovakia': 6,
 'Maldives': 1,
 'Democratic Republic of the Congo': 1,
 'Taiwan': 5,
 'Republic of Moldova': 1,
 'Hong Kong (S.A.R.)': 2,
 'Argentina': 6,
 'Malta': 2,
 'Philippines': 19,
 'Peru': 1,
 'Rwanda': 1,
 'Myanmar': 5,
 'El Salvador': 0,
 'Jordan': 3,
 'Bulgaria': 6,
 'Venezuela, Bolivarian Republic of...': 2,
 'Senegal': 0,
 'Cyprus': 2,
 'Bosnia and Herzegovina': 3,
 'Uruguay': 1,
 'Timor-Leste': 0,
 'Azerbaijan': 4,
 'Albania': 0,
 'Kyrgyzstan': 0,
 'Ecuador': 1,
 "Lao People's Democratic Republic": 1,
 'Latvia': 2,
 'Uganda': 9,
 'Mongolia': 2,
 'Kosovo': 2,
 'Tunisia': 7,
 'Afghanistan': 2,
 'United Republic of Tanzania': 2,
 'Armenia': 0,
 'Bhutan': 0,
 'Iraq': 0,
 'Zimbabwe': 1,
 'The former Yugoslav Republic of Macedonia': 1,
 'Jamaica': 0,
 'Republic of Korea': 3,
 'Uzbekistan': 4,
 'Benin': 0,
 'Honduras': 0,
 'Ethiopia': 1,
 'Zambia': 0,
 'Turkmenistan': 0,
 'Qatar': 0,
 'Burundi': 0,
 'Swaziland': 0,
 'Togo': 0,
 "Côte d'Ivoire": 1,
 'Cameroon': 4,
 'Guatemala': 0,
 'Yemen': 0,
 'Haiti': 1,
 'Andorra': 0,
 'Panama': 1,
 'Oman': 1,
 'Libyan Arab Jamahiriya': 0,
 'Sierra Leone': 1,
 'Nomadic': 1,
 'Cuba': 0,
 'Congo, Republic of the...': 1,
 'San Marino': 0,
 'Mauritius': 1,
 'Iceland': 2,
 'Burkina Faso': 0,
 'Namibia': 0,
 'Angola': 1,
 'Guinea': 0,
 'Bahrain': 0,
 'Cambodia': 1,
 'Cape Verde': 0,
 'Montenegro': 0,
 'Tajikistan': 0,
 'Luxembourg': 2,
 'Nauru': 1,
 'Kuwait': 0,
 'Eritrea': 0,
 'Brunei Darussalam': 0,
 'Syrian Arab Republic': 1,
 'Gambia': 0,
 'Madagascar': 0,
 'Isle of Man': 0,
 'Barbados': 0,
 'Mali': 0,
 'Antigua and Barbuda': 0,
 'Micronesia, Federated States of...': 1,
 'Bahamas': 0,
 'Saint Vincent and the Grenadines': 0,
 'Belize': 1}

In [122]:
student_dict = {"Respondent": country_respondent.values, "Students": list(students.values()), "Country": list(students.keys())}

In [123]:
student_dict

{'Respondent': array([3120, 2112,  977,  971,  562,  472,  466,  353,  321,  300,  299,
         293,  260,  223,  206,  195,  169,  164,  157,  139,  137,  136,
         130,  128,  127,  127,  117,  117,  111,  111,  104,  102,  100,
         100,   93,   89,   89,   87,   85,   85,   81,   81,   79,   78,
          76,   74,   66,   64,   62,   57,   56,   53,   49,   48,   47,
          43,   38,   37,   36,   36,   34,   33,   32,   29,   27,   26,
          26,   26,   25,   24,   24,   23,   22,   22,   21,   20,   19,
          18,   18,   18,   17,   17,   16,   15,   14,   13,   12,   11,
          11,   11,   10,   10,   10,   10,   10,    9,    9,    8,    8,
           8,    8,    8,    8,    8,    7,    7,    7,    7,    7,    7,
           7,    7,    7,    6,    6,    6,    5,    5,    4,    4,    4,
           4,    4,    4,    4,    3,    3,    3,    3,    3,    2,    2,
           2,    2,    2,    2,    2,    2,    2,    2,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1],
       dtype=int64),
 'Students': [31,
  0,
  266,
  339,
  14,
  143,
  7,
  76,
  28,
  2,
  19,
  43,
  28,
  30,
  13,
  17,
  64,
  7,
  24,
  10,
  11,
  15,
  80,
  16,
  12,
  14,
  31,
  4,
  7,
  33,
  1,
  8,
  12,
  28,
  11,
  6,
  11,
  4,
  4,
  6,
  12,
  12,
  0,
  19,
  6,
  8,
  28,
  0,
  10,
  0,
  0,
  1,
  16,
  0,
  5,
  6,
  4,
  34,
  32,
  23,
  2,
  15,
  1,
  11,
  7,
  24,
  23,
  14,
  4,
  4,
  3,
  0,
  3,
  0,
  6,
  1,
  1,
  5,
  1,
  2,
  6,
  2,
  19,
  1,
  1,
  5,
  0,
  3,
  6,
  2,
  0,
  2,
  3,
  1,
  0,
  4,
  0,
  0,
  1,
  1,
  2,
  9,
  2,
  2,
  7,
  2,
  2,
  0,
  0,
  0,
  1,
  1,
  0,
  3,
  4,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  4,
  0,
  0,
  1,
  0,
  1,
  1,
  0,
  1,
  1,
  0,
  1,
  0,
  1,
  2,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  2,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1],
 'Country': ['Brazil',
  'Dominican Republic',
  'United States',
  'India',
  'Portugal',
  'Germany',
  'Ireland',
  'United Kingdom',
  'Spain',
  'Sudan',
  'Switzerland',
  'Netherlands',
  'Turkey',
  'Australia',
  'Mexico',
  'Israel',
  'France',
  'Serbia',
  'Bangladesh',
  'Iran',
  'Norway',
  'Greece',
  'Canada',
  'Sri Lanka',
  'Romania',
  'Russian Federation',
  'Poland',
  'Colombia',
  'Slovenia',
  'Pakistan',
  'Bolivia',
  'Finland',
  'Ukraine',
  'Nigeria',
  'Denmark',
  'Algeria',
  'Belgium',
  'Japan',
  'Georgia',
  'Lebanon',
  'Nepal',
  'Singapore',
  'Solomon Islands',
  'Kenya',
  'Thailand',
  'Malaysia',
  'Sweden',
  'Costa Rica',
  'Hungary',
  'Mozambique',
  'United Arab Emirates',
  'Estonia',
  'Czech Republic',
  'Kazakhstan',
  'Croatia',
  'New Zealand',
  'Lithuania',
  'Italy',
  'China',
  'Indonesia',
  'Belarus',
  'Morocco',
  'Paraguay',
  'Ghana',
  'South Korea',
  'Viet Nam',
  'Austria',
  'South Africa',
  'Egypt',
  'Chile',
  'Saudi Arabia',
  'Malawi',
  'Somalia',
  'Nicaragua',
  'Slovakia',
  'Maldives',
  'Democratic Republic of the Congo',
  'Taiwan',
  'Republic of Moldova',
  'Hong Kong (S.A.R.)',
  'Argentina',
  'Malta',
  'Philippines',
  'Peru',
  'Rwanda',
  'Myanmar',
  'El Salvador',
  'Jordan',
  'Bulgaria',
  'Venezuela, Bolivarian Republic of...',
  'Senegal',
  'Cyprus',
  'Bosnia and Herzegovina',
  'Uruguay',
  'Timor-Leste',
  'Azerbaijan',
  'Albania',
  'Kyrgyzstan',
  'Ecuador',
  "Lao People's Democratic Republic",
  'Latvia',
  'Uganda',
  'Mongolia',
  'Kosovo',
  'Tunisia',
  'Afghanistan',
  'United Republic of Tanzania',
  'Armenia',
  'Bhutan',
  'Iraq',
  'Zimbabwe',
  'The former Yugoslav Republic of Macedonia',
  'Jamaica',
  'Republic of Korea',
  'Uzbekistan',
  'Benin',
  'Honduras',
  'Ethiopia',
  'Zambia',
  'Turkmenistan',
  'Qatar',
  'Burundi',
  'Swaziland',
  'Togo',
  "Côte d'Ivoire",
  'Cameroon',
  'Guatemala',
  'Yemen',
  'Haiti',
  'Andorra',
  'Panama',
  'Oman',
  'Libyan Arab Jamahiriya',
  'Sierra Leone',
  'Nomadic',
  'Cuba',
  'Congo, Republic of the...',
  'San Marino',
  'Mauritius',
  'Iceland',
  'Burkina Faso',
  'Namibia',
  'Angola',
  'Guinea',
  'Bahrain',
  'Cambodia',
  'Cape Verde',
  'Montenegro',
  'Tajikistan',
  'Luxembourg',
  'Nauru',
  'Kuwait',
  'Eritrea',
  'Brunei Darussalam',
  'Syrian Arab Republic',
  'Gambia',
  'Madagascar',
  'Isle of Man',
  'Barbados',
  'Mali',
  'Antigua and Barbuda',
  'Micronesia, Federated States of...',
  'Bahamas',
  'Saint Vincent and the Grenadines',
  'Belize']}

In [89]:
df["Employment"]=='Student'

0        False
1        False
2        False
3        False
4        False
         ...
16110    False
16111    False
16112    False
16113    False
16114     True
Name: Employment, Length: 16115, dtype: bool

In [124]:
student_df = pd.DataFrame(student_dict)

In [128]:
student_df.set_index("Country", inplace=True)

In [129]:
student_df

                                    Respondent  Students
Country
Brazil                                    3120        31
Dominican Republic                        2112         0
United States                              977       266
India                                      971       339
Portugal                                   562        14
...                                        ...       ...
Antigua and Barbuda                          1         0
Micronesia, Federated States of...           1         1
Bahamas                                      1         0
Saint Vincent and the Grenadines             1         0
Belize                                       1         1

[165 rows x 2 columns]

In [125]:
# percentage knows python = part/whole*100
python_df['PctKnowsPython']=python_df['KnowsPython']/python_df['NumRespondent'] * 100

In [ ]:
python_df.head()

In [ ]:
# sorting_new_df
python_df.sort_values(by='PctKnowsPython', ascending=False,inplace=True)

In [ ]:
python_df